### ISSUE TITLE
Switch to Grit

### ISSUE THREAD

**Issue by judofyr** [judofyr/gash#1]

**Comment by oleander** [comment]
Is this project up-to-date, or should I use Grit?

Thanks.

**Comment by judofyr** [comment]
Grit is better.

**Comment by trans** [comment]
However Gash is very easy to use (IMO).

**Comment by judofyr** [comment]
Don't listen to him. He's just trying to lure you into an eternal hell.

Grit is **BETTER**.

**Comment by judofyr** [comment]
Actually, maybe @trans will make this library more useful now :-)

**Comment by trans** [comment]
Grit may be better, but I tried to convert grancher gem from gash to grit and hit the proverbial "FAIL". I may not be the worlds greatest coder, but a straight translation from one to the other you would think would be pretty basic. Of course it didn't help that grit is a bit sparse on documentation.

I will do what I can to improve Gash. I think it's simplicity is it's strength, when all the power of grit is not needed. 

Please add issues for anything you know needs attention, I will try to address. At some point I will also put together some tests.

**Comment by oleander** [comment]
@trans Sounds awesome. I'll try to contribute as much as possible.

**Comment by minad** [comment]
You can close this one, grit is obsolete. If we port it, rugged will be the way to go.
