### ISSUE TITLE
Rugged?

### ISSUE THREAD

**Issue by minad** [judofyr/gash#11]
Is this still developed? What do you think about switching to rugged? This would really make a nice and simple wrapper around it.

**Comment by trans** [comment]
Rugged looks very good. I like that it is a real binding. If rugged would also provide a higher-level interface like gash's, then there would be no question. The nice thing about gash is as it says in the readme, "It is easier to use b/c it effectively allows you to work with the files in the repo much like you would any Ruby Hash." Have a look at this to see what I mean: http://judofyr.github.com/gash/

Any possibility that rugged could provide this kind of interface?

**Comment by minad** [comment]
Yes I like that way to access data. I am working on https://github.com/minad/juno and would like to integrate gash if it is still developed. juno is a fork of moneta which you might know, but which is unmaintained. Juno has also some additional features (e.g. proxies/middlewares)

I don't think rugged will ever provide such an interface. Rugged tries to be as close as possible to the libgit implementation which is quite low-level. Therefore it would be nice to port gash to it, since rugged will be the standard ruby git library in the future (and it is a lot faster than invoking git).

**Comment by trans** [comment]
Ah, I see what you are saying. Yes, that would be a good idea. If I had the time I would definitely pursue it. Maybe Magnus has some time? Or perhaps you would like to give a go?

**Comment by minad** [comment]
I have working code in my gitwiki (https://github.com/minad/olelo/blob/master/plugins/repositories/rugged_repository.rb) which uses rugged. It should be possible to cut it out. I can do it if I have time in the next few days.

**Comment by judofyr** [comment]
Sorry, I don't have time for Gash now. :-(

**Comment by trans** [comment]
I'll put a day or two aside and see what I can get done on this. With any luck I can get it mostly done and we can go from there.

**Comment by minad** [comment]
@trans: Cool! So it seems there are a few people interested in getting this done (@hannesg, you and me)! So I would suggest we start working on it  on a separate branch.

At first we might also want to work on #12
