### ISSUE TITLE
New release w/ 1.9 fix

### ISSUE THREAD

**Issue by trans** [judofyr/gash#6]
Can we get a new release with the 1.9 fix?

Thanks.

**Comment by judofyr** [comment]
What's your RubyGems email?

**Comment by trans** [comment]
transami

**Comment by judofyr** [comment]
There. Do what you like.

**Comment by trans** [comment]
Okay then. Thanks. You okay if simplify the release management instead of using Echoe?

**Comment by judofyr** [comment]
Sure. Do exactly what you like.

**Comment by trans** [comment]
Thanks Mangus, I just released.
